apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - login-deployment.yaml
  - login-service.yaml
  - matchmakerservice-deployment.yaml
  - matchmakerservice-service.yaml
  - storeservice-deployment.yaml
  - storeservice-service.yaml
  - playerinfoservice-deployment.yaml
  - playerinfoservice-service.yaml
  - gameserver-deployment.yaml
  - gameserver-service.yaml
  - relayrouter-deployment.yaml
  - relayrouter-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - relay-deployment.yaml
  - relay-service.yaml
