apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: staging
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: login
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  