apiVersion: v1
kind: Service
metadata:
  name: matchmakerservice
  namespace: staging
spec:
  selector:
    app: matchmakerservice
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer