apiVersion: v1
kind: Service
metadata:
  name: matchmakerservice
  namespace: staging
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: matchmakerservice
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer