apiVersion: v1
kind: Service
metadata:
  name: playerinfoservice
  namespace: staging
spec:
  selector:
    app: playerinfoservice
  ports:
    - name: http
      protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP