apiVersion: v1
kind: Service
metadata:
  name: relayrouter
  namespace: staging
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: relayrouter
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer