apiVersion: v1
kind: Service
metadata:
  name: storeservice
  namespace: staging
spec:
  selector:
    app: storeservice
  ports:
    - name: http
      protocol: TCP
      port: 8081      # lokal port i cluster
      targetPort: 8080  # container lytter p√• 8080
  type: LoadBalancer