apiVersion: v1
kind: Service
metadata:
  name: storeservice
  namespace: staging
spec:
  selector:
    app: storeservice
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer